/* Auto-generated by genmsg_cpp for file /home/haquang/fuerte_workspace/sandbox/brl_teleop_msgs/msg/Common.msg */
#ifndef BRL_TELEOP_MSGS_MESSAGE_COMMON_H
#define BRL_TELEOP_MSGS_MESSAGE_COMMON_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace brl_teleop_msgs
{
template <class ContainerAllocator>
struct Common_ {
  typedef Common_<ContainerAllocator> Type;

  Common_()
  : header()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  Common_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;


  typedef boost::shared_ptr< ::brl_teleop_msgs::Common_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_teleop_msgs::Common_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Common
typedef  ::brl_teleop_msgs::Common_<std::allocator<void> > Common;

typedef boost::shared_ptr< ::brl_teleop_msgs::Common> CommonPtr;
typedef boost::shared_ptr< ::brl_teleop_msgs::Common const> CommonConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::brl_teleop_msgs::Common_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::brl_teleop_msgs::Common_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace brl_teleop_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Common_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Common_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::brl_teleop_msgs::Common_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75f40115cb5a29c0ceea66f491a5e1a3";
  }

  static const char* value(const  ::brl_teleop_msgs::Common_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x75f40115cb5a29c0ULL;
  static const uint64_t static_value2 = 0xceea66f491a5e1a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_teleop_msgs::Common_<ContainerAllocator> > {
  static const char* value() 
  {
    return "brl_teleop_msgs/Common";
  }

  static const char* value(const  ::brl_teleop_msgs::Common_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::brl_teleop_msgs::Common_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This is definition of common message.\n\
Header header\n\
float32 x	\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::brl_teleop_msgs::Common_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::brl_teleop_msgs::Common_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::brl_teleop_msgs::Common_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::brl_teleop_msgs::Common_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Common_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_teleop_msgs::Common_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::brl_teleop_msgs::Common_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BRL_TELEOP_MSGS_MESSAGE_COMMON_H

