/* Auto-generated by genmsg_cpp for file /home/haquang/fuerte_workspace/sandbox/brl_teleop_msgs/msg/Energy.msg */
#ifndef BRL_TELEOP_MSGS_MESSAGE_ENERGY_H
#define BRL_TELEOP_MSGS_MESSAGE_ENERGY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace brl_teleop_msgs
{
template <class ContainerAllocator>
struct Energy_ {
  typedef Energy_<ContainerAllocator> Type;

  Energy_()
  : header()
  , Ex(0.0)
  , Ey(0.0)
  , Ez(0.0)
  {
  }

  Energy_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , Ex(0.0)
  , Ey(0.0)
  , Ez(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _Ex_type;
  float Ex;

  typedef float _Ey_type;
  float Ey;

  typedef float _Ez_type;
  float Ez;


  typedef boost::shared_ptr< ::brl_teleop_msgs::Energy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_teleop_msgs::Energy_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Energy
typedef  ::brl_teleop_msgs::Energy_<std::allocator<void> > Energy;

typedef boost::shared_ptr< ::brl_teleop_msgs::Energy> EnergyPtr;
typedef boost::shared_ptr< ::brl_teleop_msgs::Energy const> EnergyConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::brl_teleop_msgs::Energy_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::brl_teleop_msgs::Energy_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace brl_teleop_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Energy_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Energy_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::brl_teleop_msgs::Energy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6d27ae3a18c83ba5c7546d84ca7c4e9";
  }

  static const char* value(const  ::brl_teleop_msgs::Energy_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd6d27ae3a18c83baULL;
  static const uint64_t static_value2 = 0x5c7546d84ca7c4e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_teleop_msgs::Energy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "brl_teleop_msgs/Energy";
  }

  static const char* value(const  ::brl_teleop_msgs::Energy_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::brl_teleop_msgs::Energy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This is definition of 3D energy message.\n\
Header header\n\
float32 Ex\n\
float32 Ey\n\
float32 Ez\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::brl_teleop_msgs::Energy_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::brl_teleop_msgs::Energy_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::brl_teleop_msgs::Energy_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::brl_teleop_msgs::Energy_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.Ex);
    stream.next(m.Ey);
    stream.next(m.Ez);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Energy_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_teleop_msgs::Energy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::brl_teleop_msgs::Energy_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Ex: ";
    Printer<float>::stream(s, indent + "  ", v.Ex);
    s << indent << "Ey: ";
    Printer<float>::stream(s, indent + "  ", v.Ey);
    s << indent << "Ez: ";
    Printer<float>::stream(s, indent + "  ", v.Ez);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BRL_TELEOP_MSGS_MESSAGE_ENERGY_H

