/* Auto-generated by genmsg_cpp for file /home/haquang/fuerte_workspace/sandbox/brl_teleop_msgs/msg/Force.msg */
#ifndef BRL_TELEOP_MSGS_MESSAGE_FORCE_H
#define BRL_TELEOP_MSGS_MESSAGE_FORCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace brl_teleop_msgs
{
template <class ContainerAllocator>
struct Force_ {
  typedef Force_<ContainerAllocator> Type;

  Force_()
  : header()
  , fx(0.0)
  , fy(0.0)
  , fz(0.0)
  {
  }

  Force_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , fx(0.0)
  , fy(0.0)
  , fz(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _fx_type;
  float fx;

  typedef float _fy_type;
  float fy;

  typedef float _fz_type;
  float fz;


  typedef boost::shared_ptr< ::brl_teleop_msgs::Force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_teleop_msgs::Force_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Force
typedef  ::brl_teleop_msgs::Force_<std::allocator<void> > Force;

typedef boost::shared_ptr< ::brl_teleop_msgs::Force> ForcePtr;
typedef boost::shared_ptr< ::brl_teleop_msgs::Force const> ForceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::brl_teleop_msgs::Force_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::brl_teleop_msgs::Force_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace brl_teleop_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Force_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Force_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::brl_teleop_msgs::Force_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0c34800d32e0dfa4e955590a01c3d176";
  }

  static const char* value(const  ::brl_teleop_msgs::Force_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0c34800d32e0dfa4ULL;
  static const uint64_t static_value2 = 0xe955590a01c3d176ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_teleop_msgs::Force_<ContainerAllocator> > {
  static const char* value() 
  {
    return "brl_teleop_msgs/Force";
  }

  static const char* value(const  ::brl_teleop_msgs::Force_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::brl_teleop_msgs::Force_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This is definition of 3D force message.\n\
Header header\n\
float32 fx\n\
float32 fy\n\
float32 fz\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::brl_teleop_msgs::Force_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::brl_teleop_msgs::Force_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::brl_teleop_msgs::Force_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::brl_teleop_msgs::Force_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.fx);
    stream.next(m.fy);
    stream.next(m.fz);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Force_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_teleop_msgs::Force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::brl_teleop_msgs::Force_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fx: ";
    Printer<float>::stream(s, indent + "  ", v.fx);
    s << indent << "fy: ";
    Printer<float>::stream(s, indent + "  ", v.fy);
    s << indent << "fz: ";
    Printer<float>::stream(s, indent + "  ", v.fz);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BRL_TELEOP_MSGS_MESSAGE_FORCE_H

