/* Auto-generated by genmsg_cpp for file /home/haquang/fuerte_workspace/sandbox/brl_teleop_msgs/msg/Vel.msg */
#ifndef BRL_TELEOP_MSGS_MESSAGE_VEL_H
#define BRL_TELEOP_MSGS_MESSAGE_VEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace brl_teleop_msgs
{
template <class ContainerAllocator>
struct Vel_ {
  typedef Vel_<ContainerAllocator> Type;

  Vel_()
  : header()
  , deltaX(0.0)
  , deltaY(0.0)
  , deltaZ(0.0)
  {
  }

  Vel_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , deltaX(0.0)
  , deltaY(0.0)
  , deltaZ(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _deltaX_type;
  float deltaX;

  typedef float _deltaY_type;
  float deltaY;

  typedef float _deltaZ_type;
  float deltaZ;


  typedef boost::shared_ptr< ::brl_teleop_msgs::Vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brl_teleop_msgs::Vel_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Vel
typedef  ::brl_teleop_msgs::Vel_<std::allocator<void> > Vel;

typedef boost::shared_ptr< ::brl_teleop_msgs::Vel> VelPtr;
typedef boost::shared_ptr< ::brl_teleop_msgs::Vel const> VelConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::brl_teleop_msgs::Vel_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::brl_teleop_msgs::Vel_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace brl_teleop_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Vel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::brl_teleop_msgs::Vel_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::brl_teleop_msgs::Vel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "06d63fb4efd8aa0a11df71e3ff9e7314";
  }

  static const char* value(const  ::brl_teleop_msgs::Vel_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x06d63fb4efd8aa0aULL;
  static const uint64_t static_value2 = 0x11df71e3ff9e7314ULL;
};

template<class ContainerAllocator>
struct DataType< ::brl_teleop_msgs::Vel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "brl_teleop_msgs/Vel";
  }

  static const char* value(const  ::brl_teleop_msgs::Vel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::brl_teleop_msgs::Vel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This is definition of 3D velocity message.\n\
Header header\n\
float32 deltaX		\n\
float32 deltaY\n\
float32 deltaZ\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::brl_teleop_msgs::Vel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::brl_teleop_msgs::Vel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::brl_teleop_msgs::Vel_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::brl_teleop_msgs::Vel_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.deltaX);
    stream.next(m.deltaY);
    stream.next(m.deltaZ);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Vel_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brl_teleop_msgs::Vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::brl_teleop_msgs::Vel_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "deltaX: ";
    Printer<float>::stream(s, indent + "  ", v.deltaX);
    s << indent << "deltaY: ";
    Printer<float>::stream(s, indent + "  ", v.deltaY);
    s << indent << "deltaZ: ";
    Printer<float>::stream(s, indent + "  ", v.deltaZ);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BRL_TELEOP_MSGS_MESSAGE_VEL_H

